apiVersion: apps/v1  # Версия API Kubernetes, используемая для создания объекта Deployment
kind: Deployment  # Тип объекта, который мы создаем (Deployment)
metadata:
  name: postgres  # Имя развертывания, используемое для его идентификации
spec:
  replicas: 1  # Количество реплик (подов), которые должны быть запущены
  selector:
    matchLabels:
      app: postgres  # Селектор для определения, какие поды управляются этим развертыванием
  template:
    metadata:
      labels:
        app: postgres  # Метка для подов, создаваемых этим развертыванием
    spec:
      containers:
        - name: postgres-container  # Имя контейнера
          image: postgres:14  # Образ контейнера PostgreSQL версии 14
          resources:
            limits:  # Ограничения ресурсов для контейнера
              cpu: 200m  # Максимальное количество CPU, которое может использовать контейнер
              memory: 256Mi  # Максимальное количество памяти, которое может использовать контейнер
            requests:  # Запросы ресурсов для контейнера
              cpu: 100m  # Минимальное количество CPU, которое гарантируется контейнеру
              memory: 128Mi  # Минимальное количество памяти, которое гарантируется контейнеру
          imagePullPolicy: "IfNotPresent"  # Политика загрузки образа (загружать только если образ отсутствует)
          ports:
            - containerPort: 5432  # Порт, на котором контейнер будет слушать входящие запросы (стандартный порт PostgreSQL)
          envFrom:
            - configMapRef:  # Ссылка на ConfigMap для передачи переменных окружения в контейнер
                name: postgres-configmap  # Имя ConfigMap, из которого будут взяты переменные окружения
