apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  labels:
    app: postgres
type: Opaque
stringData:
  POSTGRES_USER: "postgres"  # Имя пользователя для PostgreSQL
  POSTGRES_PASSWORD: "test123@password"  # Пароль для PostgreSQL
