apiVersion: apps/v1
kind: Deployment
metadata:
  name: init-service
  labels:
    app: init-service
    environment: production
spec:
  replicas: 1
  selector:
    matchLabels:
      app: init-service
  template:
    metadata:
      labels:
        app: init-service
    spec:
      containers:
        - name: init-container
          image: alpine:latest
          command: ["sh", "-c", "echo 'Initialization complete'"]