apiVersion: v1
kind: Secret
metadata:
  name: nextcloud-secret  # Название секрета, который содержит конфиденциальные данные для Nextcloud.
  labels:
    app: nextcloud  # Метка для идентификации приложения, к которому относится секрет.
type: Opaque  # Тип секрета, указывающий, что данные не имеют специального формата.
stringData:
  NEXTCLOUD_ADMIN_PASSWORD: "next879rtfpass@"  # Пароль администратора Nextcloud.
  POSTGRES_DB: "postgres"  # Имя базы данных Nextcloud, замените по желанию
  POSTGRES_USER: "postgres"  # Имя пользователя базы данных, замените по желанию
  POSTGRES_PASSWORD: "test123@password"  # Пароль для базы данных, замените на свой
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: nextcloud  # Название развертывания для Nextcloud.
  labels:
    app: nextcloud  # Метка для идентификации приложения в Kubernetes.
spec:
  replicas: 1  # Количество реплик (экземпляров) приложения, которые будут запущены.
  selector:
    matchLabels:
      app: nextcloud  # Условие для выбора подов, соответствующих этому развертыванию.
  template:
    metadata:
      labels:
        app: nextcloud  # Метка, которая будет применена к создаваемым подам.
    spec:
      containers:
        - name: nextcloud  # Имя контейнера с приложением Nextcloud.
          image: docker.io/nextcloud:stable-apache  # Образ Docker для Nextcloud с Apache.
          resources:
            limits:
              cpu: 500m  # Максимальное количество CPU, которое может использовать контейнер.
              memory: 256Mi  # Максимальное количество памяти, которое может использовать контейнер.
            requests:
              cpu: 250m  # Минимальное количество CPU, которое будет выделено контейнеру.
              memory: 128Mi  # Минимальное количество памяти, которое будет выделено контейнеру.
          ports:
            - name: http
              containerPort: 80  # Порт, на котором приложение будет доступно внутри контейнера.
              protocol: TCP
          env:
            - name: NEXTCLOUD_UPDATE
              value: '1'  # Включение автоматических обновлений Nextcloud.
            - name: ALLOW_EMPTY_PASSWORD
              value: 'yes'  # Разрешение использования пустых паролей для пользователей (не рекомендуется в продакшене).
            - name: POSTGRES_HOST
              value: postgres-service  # Имя сервиса PostgreSQL для подключения к базе данных.
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: postgres-configmap  # Ссылка на ConfigMap для получения имени базы данных.
                  key: POSTGRES_DB
            - name: NEXTCLOUD_TRUSTED_DOMAINS
              value: "127.0.0.1"  # Доверенные домены для доступа к Nextcloud (добавьте свои домены).
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: postgres-configmap  # Ссылка на ConfigMap для получения имени пользователя базы данных.
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: postgres-configmap  # Ссылка на ConfigMap для получения пароля пользователя базы данных.
                  key: POSTGRES_PASSWORD
            - name: NEXTCLOUD_ADMIN_USER
              value: any_name_you_want  # Имя администратора Nextcloud. Замените на желаемое имя.
            - name: NEXTCLOUD_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: nextcloud-secret  # Ссылка на секрет для получения пароля администратора.
                  key: NEXTCLOUD_ADMIN_PASSWORD
          imagePullPolicy: IfNotPresent  # Политика извлечения образа (не извлекать, если образ уже есть).
      restartPolicy: Always  # Политика перезапуска подов (всегда перезапускать при сбое).
      dnsPolicy: ClusterFirst  # Политика DNS (использовать DNS-кластер в первую очередь).
