apiVersion: v1  # Версия API Kubernetes, используемая для создания объекта
kind: Service  # Тип объекта, который мы создаем (Service)
metadata:
  name: postgres-service  # Имя сервиса, используемое для его идентификации
  labels:
    app: postgres  # Метка для группировки и идентификации объектов в Kubernetes
spec:
  type: NodePort  # Тип сервиса, который позволяет доступ к приложению через порт на узле
  ports:
    - port: 5432  # Порт, на котором сервис будет слушать входящие запросы
      # Этот порт соответствует стандартному порту PostgreSQL
  selector:
    app: postgres  # Селектор для связывания сервиса с подами, которые имеют метку app: postgres
